<?php

namespace Database\Seeders;

class PageBodies
{
    public static function get(string $slug): ?string
    {
        return self::bodies()[$slug] ?? null;
    }

    private static function bodies(): array
    {
        return [
            'healthline' => <<<'HTML'
<section class="content-section"><h2>Comprehensive and Trusted Service Directory</h2><p class="lead">An authoritative health service directory that makes navigating the health care system easier</p><p>With 47,000 detailed records for home, community, primary, acute and long-term care services, Our online service directory is the most widely used, Ontario-wide online system navigation tool, powering digital health tools like Health Care Options. It enables patients and caregivers to locate services and helps system navigators and care coordinators integrate care for patients from hospital to home and everywhere in between.</p><blockquote><p>&ldquo;Thehealthline.ca has been invaluable to us in many ways. We have been successful in finding great candidates by posting job ads, our providers use the site to search for the best community resources for patients and the local healthcare news and events pages are always up to date.&rdquo;</p><cite>&mdash; London Family Health Team</cite></blockquote></section>
<section class="content-section"><h2>Flexible Information Presentation</h2><p>More than a database, the service directory can be adapted to show relevant information in ways that meet user preferences and needs. Specific service types, patient populations and targeted geographical regions can all be customized, along with tailored user interfaces for mobile and desktop.</p></section>
<section class="content-section"><h2>Plain Language for Ease-of-Use</h2><p>Patients need clear and simple information in order to make the best health care decisions. Our rigorous standards and template text ensure consistent and easily understood descriptions.</p></section>
<section class="content-section"><h2>Robust Information Management</h2><p>All information is validated and refreshed regularly to make sure services are accurately described and up to date and that supporting information is correct. Strong data quality standards and clear inclusion criteria ensure that services are relevant to users.</p></section>
<section class="content-section"><h2>Inter-operable</h2><p>The service directory is web-based and is thus inter-operable with electronic health records (EHR) systems. In addition, application programming interfaces (API) can be built to integrate into existing websites.</p><p><a class="btn btn-primary" href="https://thlin.ca/Uploads/ContentDocuments/THL%20infosheet.pdf" target="_blank" rel="noopener">Download infosheet (PDF)</a></p></section>
HTML,
            'healthchat' => <<<'HTML'
<section class="content-section"><h2>Collaboration Made Easy</h2><p class="lead">A simple tool to bring your teams together in one place</p><p>healthchat.ca quickly and easily enables online collaboration and integration, wherever team members are located. Web-based, healthchat.ca supports document sharing, conversations and events tracking to facilitate multi-disciplinary project management, team organization and virtual communities of practice.</p><blockquote><p>&ldquo;I don't think our staff would be as nimble, communicative, efficient and connected without Healthchat.ca.&rdquo;</p><cite>&mdash; Behavioural Supports Ontario</cite></blockquote></section>
<section class="content-section"><h2>Simple and Intuitive</h2><p>healthchat.ca offers a simple user interface with easy-to-use administrative tools and a minimal learning curve. You can quickly establish and configure your group, invite members and get to work.</p></section>
<section class="content-section"><h2>Powerful Functionality</h2><p>Whatever you need to do to grow your group, healthchat.ca can help. Upload documents, drop events into a calendar (and integrate it into your Outlook or other mail programs), start conversations, invite members, it's all available in the core platform. If that's not enough, we can customize a solution for you to meet your specific needs.</p></section>
<section class="content-section"><h2>Web-Based</h2><p>healthchat.ca is accessible anywhere you are. There's no need for dedicated servers, software downloads or installation. All you need is a web browser and an Internet connection.</p></section>
<section class="content-section"><h2>Secure</h2><p>Your data is safe with healthchat.ca. With servers located in Canada and strong security, you can be confident that all the information you share is visible and accessible only by group members. As an administrator, you're in control of who joins your groups.</p><p><a class="btn btn-primary" href="/products/healthchat-features">Learn more about features</a></p></section>
HTML,
            'healthchat-features' => <<<'HTML'
<section class="content-section"><h2>healthchat.ca Features</h2><p>Explore the core capabilities that make healthchat.ca a trusted collaboration platform for health and social service teams across Ontario.</p><ul><li>Document sharing and team file libraries</li><li>Threaded conversations and group messaging</li><li>Shared calendars with Outlook integration</li><li>Member administration and access controls</li><li>Custom configurations for specialized workflows</li></ul><p><a class="btn btn-primary" href="/products/healthchat">Back to healthchat.ca overview</a></p></section>
HTML,
            'patient-portals' => <<<'HTML'
<section class="content-section"><h2>Connecting Patients to Services</h2><p class="lead">Useful and usable websites to help patients and caregivers find the care they need</p><p>We build custom websites that support patients on their care journey with relevant information about health and social services as well as additional information resources. We present this content in accessible and highly usable web tools, built for specific patient needs and preferences.</p></section>
<section class="content-section"><h2>User-friendly</h2><p>The care journey is challenging enough. Finding information about the services you need shouldn't be. We place a strong emphasis on usability, working to uncover patient needs and preferences through a discovery phase and reflecting those findings in designed user interfaces that are intuitive and aligned with search behaviour. Co-designing websites enables us to build effective and intuitive site navigation pathways that are simple to understand and use. As always, our tools are fully AODA-compliant and work equally well on mobile and desktop.</p></section>
<section class="content-section"><h2>Tailored</h2><p>Every patient journey is different. We build unique offerings that acknowledge this fact and address the specific needs of patient populations, whether distinguished by geography, condition, age or a combination of other factors.</p></section>
<section class="content-section"><h2>Information-Rich</h2><p>We create information hubs that provide deep data on health and social services, powered by our service directory database and filtered to provide relevant results for specific patient and caregiver needs. Additional resources can also be integrated to support your teams.</p></section>
<section class="content-section"><h2>Healthcare and More</h2><p>We recognize that a holistic view of health care must address the needs of the whole person. That's why our comprehensive services directory captures key information not only about available health services but also social services and supports that enhance other determinants of health.</p></section>
<section class="content-section"><h2>Solutions in Action</h2><ul><li><a href="http://www.behaviouralsupportsontario.ca/" target="_blank" rel="noopener">Behavioural Supports Ontario</a></li><li><a href="https://www.caregiverexchange.ca/" target="_blank" rel="noopener">Caregiver Exchange</a></li><li><a href="http://swhealthyaging.ca/" target="_blank" rel="noopener">South West Healthy Aging</a></li></ul></section>
HTML,
            'provider-portals' => <<<'HTML'
<section class="content-section"><h2>Connecting Providers to Information</h2><p class="lead">Powerful websites to help health care professionals work better</p><p>We build tailored websites that provide key information and resources to enable system navigators, care coordinators and planners to work effectively and efficiently. With exceptional functionality and deep data, these tools put relevant information at the fingertips of health care professionals and connect them to their peers.</p><blockquote><p>&ldquo;thehealthline.ca really understood what we were doing and were able to take our ideas and run with them.&rdquo;</p><cite>&mdash; Assess &amp; Restore</cite></blockquote></section>
<section class="content-section"><h2>User-Friendly</h2><p>Our web tools mirror your real-world workflows and practices so that there's no learning curve for users. We work hard to co-design and craft websites that reflect user expectations, preferences and needs. And of course, beyond intuitive interfaces and effective site navigation, our tools are fully AODA-compliant and work equally well on mobile and desktop.</p></section>
<section class="content-section"><h2>Information-Rich</h2><p>We create information hubs that provide deep data on health and social services, powered by our service directory database and filtered to provide relevant results for your specific needs. Additional resources can also be integrated to support your teams.</p></section>
<section class="content-section"><h2>Powerful and Evidence-Based</h2><p>Sites feature customized functionality, such as decision trees, treatment protocols and best practices to identify patient risk levels and support evidence-based care.</p></section>
<section class="content-section"><h2>Connected</h2><p>Our web tools are designed to bring teams together and furnish them with the tools they need to get the job done, wherever team members are located. Local, regional and provincial networks, formal and informal, can be supported by our provider websites. For added capabilities, consider using our HealthChat online collaboration tool to unite your teams.</p></section>
<section class="content-section"><h2>Built for Social Prescribing</h2><p>Better outcomes come from treating the whole person. Our comprehensive services directory includes health and social services as well as community supports and the &ldquo;clipboard&rdquo; feature embedded on many websites allows system navigators and care coordinators to easily create custom service lists that meet the social and health care needs of each patient. Frequently accessed services can also be quickly bookmarked.</p></section>
<section class="content-section"><h2>Solutions in Action</h2><ul><li><a href="http://www.swassessandrestore.ca/" target="_blank" rel="noopener">South West Assess and Restore</a></li><li><a href="https://gtarehabfinder.ca/" target="_blank" rel="noopener">GTA Rehab Finder</a></li><li><a href="http://www.swrwoundcareprogram.ca/" target="_blank" rel="noopener">South West Regional Wound Care Program</a></li></ul></section>
HTML,
            'support-training' => <<<'HTML'
<section class="content-section"><h2>Let's Work Together</h2><p>Get the most from our powerful tools. Whether you're new to our offerings or want to explore their more advanced functionality, our training and support will help. We offer regular webinars to familiarize you with our service directory and its capabilities. In addition, we're here to support our customers with specific needs.</p><p>To book training or request support: <a href="mailto:admin@thehealthline.ca">admin@thehealthline.ca</a><br>For support with healthchat.ca: <a href="mailto:info@healthchat.ca">info@healthchat.ca</a></p></section>
<section class="content-section"><h2>Need Help Navigating thehealthline.ca?</h2><p>There is a regional thehealthline.ca website in every part of the province. If you have never visited your local website, or you would like to learn more about how to submit, find, and share information on the website, check out our quick tutorial videos.</p><div class="card-grid"><div class="card"><h3>Events</h3><p>Get the word out to the community on our events page!</p><a href="https://www.youtube.com/watch?v=uaDB6Va1lVg" target="_blank" rel="noopener">Watch video</a></div><div class="card"><h3>Careers</h3><p>Submit job posts for health and social service positions!</p><a href="https://www.youtube.com/watch?v=vFmzutWD6sU" target="_blank" rel="noopener">Watch video</a></div><div class="card"><h3>News</h3><p>Learn how to find health and social services near you!</p><a href="https://www.youtube.com/watch?v=5g1UDrEuldE" target="_blank" rel="noopener">Watch video</a></div></div><p><a href="https://www.youtube.com/watch?v=4ARBEGh6TS4&amp;list=PUtEEv6f_gTKOoFKPmV-cgdw" target="_blank" rel="noopener">View full tutorial playlist</a></p></section>
HTML,
            'information-management' => <<<'HTML'
<section class="content-section"><h2>Connecting Patients to Services</h2><p class="lead">Rigorous and disciplined processes</p><p>We take a principled approach to data management, informed by industry best practices. This includes collecting, cleaning, validating, organizing, displaying and sharing information. We do all of this to support our comprehensive, trusted catalogue of health and social services resources available in Ontario. While much of this work happens behind the scenes, we support clients with specific data needs, whether information management consulting, custom data collection or other aspects of information management.</p></section>
<section class="content-section"><h2>Data Needs Assessment</h2><p>Our data science experts and information management librarians can help you identify your information needs. Through rigorous gap analysis and other methods, we can provide clarity to guide data partnering and data collection efforts.</p></section>
<section class="content-section"><h2>Data Collection</h2><p>With two decades of experience in collecting and validating services data, we're well-equipped to obtain the information you need. Whether it's information to serve specific populations or topics, custom data fields or incorporating specific coding, we can help.</p></section>
<section class="content-section"><h2>Data Curation</h2><p>We're strong believers is open data and data sharing. But, because not all data are collected in the same way, we take steps to curate content from a range of sources, clean and validate it and harmonize it with our own data. This reduces duplication while still ensuring high quality.</p></section>
<section class="content-section"><h2>Information Management</h2><p>There's a reason our provincial service directory is a trusted resource – behind it are strong information standards that guide the work of collecting, validating, organizing and sharing it. Thoughtful categorization, data quality standards, style guides and clear rules governing data integration from diverse sources, data cleaning and validation (machine and human) all ensure an accurate and current end product.</p></section>
HTML,
            'portfolio' => <<<'HTML'
<section class="content-section"><p>Mapping the mosaic of services available within your community and presenting the information effectively, takes careful work. We can help. Whether you're enhancing an existing community information tool or building patient-centered websites, featuring tools to help find condition-specific information, our tailored sites are built to meet user needs. Simple, easy to use, and information-rich.</p></section>
HTML,
            'resources' => <<<'HTML'
<section class="content-section"><article><h2>Not All Service Directories Are the Same</h2><p>Patients and families often struggle to find the health care and social services they need. There are many places to look, and many services to sift through. So how do you find the information you need, quickly and effectively? All directories are not created equal.</p><p><a class="btn btn-primary" href="/products/resources/service-directories">Read more</a></p></article></section>
HTML,
            'service-directories' => <<<'HTML'
<section class="content-section"><h2>Not All Service Directories Are the Same</h2><p>Patients and families often struggle to find the health care and social services they need. There are many places to look, and many services to sift through. So how do you find the information you need, quickly and effectively?</p><p>All directories are not created equal. A trusted provincial service directory brings rigorous data standards, plain language, regular validation, and interoperability with the tools patients and providers already use.</p><p><a href="/products/healthline">Learn about thehealthline.ca</a></p></section>
HTML,
            'health-care' => <<<'HTML'
<section class="content-section"><h2>A Wealth of Digital Tools to Support Your Work</h2><p class="lead">Digital health solutions that help providers work better</p><p>Online service directories that help people find health care alternatives to the hospital emergency department. Deep data collection to support seasonal surge response efforts. Tailored websites that empower health care providers. A collaboration tool that makes virtual communities of practice more efficient and effective. Patient-focused web resources that target specific populations (age, geography, condition) and support their care journeys. Whatever challenge you face, we've got a solution.</p></section>
<section class="content-section"><h2>Health System Navigation Tools</h2><p>Whether you're a care coordinator, patient navigator or health care administrator, our online service directory can help. With 47,000 detailed records, it provides a comprehensive map of health care, spanning the province. Use it to connect patients to care in their communities, divert patients from the emergency department by providing health care alternatives, and support your system planning work.</p><p><a href="/products/healthline">Learn more about thehealthline.ca</a></p></section>
<section class="content-section"><h2>Social Prescribing Capabilities</h2><p>We've built enhanced functionality into our provider-focused websites that allows care coordinators, system navigators and discharge planners to find support services in the community and connect patients to them. Capturing social and community support services in our powerful database enables you to address many of the social determinants of health.</p></section>
<section class="content-section"><h2>Data-Rich Web Tools for Providers</h2><p>Our provider-focused websites put essential information at your fingertips. Co-designed to reflect your workflow and integrating not only searchable health services information but also best practices and decision support tools, our specialized websites can help support your care teams.</p><p><a href="/products/provider-portals">Learn more</a></p></section>
<section class="content-section"><h2>Patient-Centered Websites</h2><p>Patients and caregivers need help along their care journey. Our patient-centered websites can help. Featuring tools to help them find the services they need and condition-specific information, our tailored sites are built to meet user needs. Simple, easy to use, and information-rich, they can help patients manage a chronic condition or recover their health.</p><p><a href="/products/patient-portals">Learn more</a></p></section>
<section class="content-section"><h2>Surge Response Support</h2><p>A key element in anticipating and responding to seasonal surges in health care services demand is communicating health care options. We support your work by performing deep data collection to document service availability, gathering holiday opening hours, and sharing it online with patients and caregivers.</p></section>
<section class="content-section"><h2>See it in Action</h2><ul><li><a href="https://www.nsmhealthline.ca/libraryContent.aspx?id=21592" target="_blank" rel="noopener">Find health services for Indigenous Peoples in NSM</a></li><li><a href="http://www.swassessandrestore.ca/" target="_blank" rel="noopener">South West Assess and Restore</a></li></ul></section>
HTML,
            'municipalities' => <<<'HTML'
<section class="content-section"><h2>Accessible Information to Empower Citizens</h2><p class="lead">Citizen-centered community information solutions</p><p>From transportation options to community activities and social supports, people need to be able to quickly and easily find services in their communities. The challenge is that these services are provided by a diverse array of organizations, public and private sector. Bringing all the relevant information together in one place and presenting it in a useful and usable way is essential to creating a valuable and lasting community information resource. Our data expertise and website development capabilities enable us to deliver solutions that will empower your community.</p><blockquote><p>&ldquo;The team at thehealthline.ca has been phenomenal. Our expectations have been exceeded. It's been a great relationship and we've been able to show innovation together in this joint collaboration.&rdquo;</p><cite>&mdash; Age-Friendly Sarnia-Lambton</cite></blockquote></section>
<section class="content-section"><h2>Community Information Resources</h2><p>Mapping the mosaic of services available within your community and presenting the resulting information effectively, takes careful work. We can help. Whether you're enhancing an existing community information tool or building a new one, addressing the needs of the whole community or focusing on specific users (like parents, youth or seniors) we can bring our information management experience and website building capacity to bear to help you succeed.</p></section>
<section class="content-section"><h2>Age-friendly Enablers</h2><p>Earning the age-friendly designation is a compelling goal for communities, signaling your commitment to a growing part of the population as well as to the principles that underpin a supportive and welcoming seniors-oriented municipality. As the World Health Organization has noted, accessing information about a range of supports in the community is essential. We can help by leveraging our database of services, performing custom data collection and organization and building accessible online and offline information tools to empower seniors.</p><p><a href="https://thlin.ca/Uploads/ContentDocuments/DC_AFC_White-Paper_2019-09-30.pdf" target="_blank" rel="noopener">Age-friendly communities white paper (PDF)</a></p></section>
<section class="content-section"><h2>See it in Action</h2><ul><li><a href="http://www.informationlondon.ca/" target="_blank" rel="noopener">Information London</a></li><li><a href="https://agefriendlysarnialambton.ca/" target="_blank" rel="noopener">Age-Friendly Sarnia-Lambton</a></li></ul></section>
HTML,
            'social-services' => <<<'HTML'
<section class="content-section"><h2>An Array of Digital Tools to Support Your Work</h2><p class="lead">Digital solutions to empower social services delivery</p><p>Empower social inclusion for seniors. Connect clients to social and health services near them. Target the needs of specific populations and find the services that support their journeys. Collaborate effectively and efficiently with colleagues anywhere in the province. These are some of the benefits we offer community and social services professionals through our digital tools.</p><blockquote><p>&ldquo;Our staff report that the tool is easy to use and has become a frequently utilized resource for our organization.&rdquo;</p><cite>&mdash; Métis Nation</cite></blockquote></section>
<section class="content-section"><h2>Community and Social Services System Navigation Tools</h2><p>Whether you're working with people with disabilities, supporting newcomers to Canada, helping children and youth or working to solve a myriad of challenges, our online service directory can help. With 47,000 detailed records, it provides a comprehensive map of social, community and health care services, spanning the province.</p><p><a href="/products/healthline">Learn more</a></p></section>
<section class="content-section"><h2>Social Prescribing Capabilities</h2><p>We've built enhanced functionality into our provider-focused websites that allows community and social services professionals to find support services in the community and connect patients to them.</p></section>
<section class="content-section"><h2>Data-rich Web Tools for Providers</h2><p>Our provider-focused websites put essential information at your fingertips. Co-designed to reflect your work flow and integrating not only searchable services information but also best practices and decision support tools, our specialized websites can help support your teams.</p></section>
<section class="content-section"><h2>User-Centered Websites</h2><p>Whether it's recovery from addictions, coping with a disability, or adjusting to life in a new country, clients and families help along their journey. Our client-centered websites can help.</p><p><a href="/products/healthline">Learn more</a></p></section>
<section class="content-section"><h2>Intuitive Online Tool to Power Collaboration</h2><p>healthchat.ca quickly and easily enables online collaboration and integration, wherever team members are located.</p><p><a href="/products/healthchat">Learn more</a></p></section>
<section class="content-section"><h2>See it in Action</h2><ul><li><a href="https://www.nsmhealthline.ca/libraryContent.aspx?id=21592" target="_blank" rel="noopener">Find health services for Indigenous Peoples in NSM</a></li><li><a href="https://connect.northeasthealthline.ca/" target="_blank" rel="noopener">connect.northeasthealthline.ca</a></li></ul></section>
HTML,
            'ontario-health-teams' => <<<'HTML'
<section class="content-section"><h2>A Suite of Powerful Tools to Support your OHT</h2><p class="lead">Empowering system navigation and integration</p><p>Ontario's health care system is transforming with the introduction of a model of accountable care with the goals of enhancing integration and making the patient journey more seamless. Information is an engine of this transformation. We can help your OHT from planning through to operations by providing essential information about available services and practical tools to support system navigation services. Easily implemented, comprehensive and fully interoperable, our solutions will help you grow your OHT quickly and effectively.</p></section>
<section class="content-section"><h2>Asset Mapping</h2><p>With 47,000 health and social services records in our system, we offer a comprehensive and highly-detailed view of the assets in your catchment area, as well as those that serve it. Our mapping capabilities enable us to target this information right down to the neighbourhood level.</p></section>
<section class="content-section"><h2>System Navigation</h2><p>Support your care coordinators, system navigators and discharge planners in their work integrating care. Empower your patients with a 24/7 online system navigation tool. Our comprehensive and trusted service directory, coupled with our website development capabilities, enables us to craft innovative and practical system navigation solutions for patients and health care professionals alike.</p></section>
<section class="content-section"><h2>Patient Portal Data Integration</h2><p>We've integrated our service directory records with a range of patient and provider tools, including the Ministry of Health's Health Care Options resource and the Ontario Telemedicine Network's Health Services Directory. We can do the same for your OHT through data exports, Application Programming Interfaces (APIs) or via custom websites.</p></section>
<section class="content-section"><h2>Social Prescribing</h2><p>Integrate care and address the social determinants of health using our provider-focused websites, which feature social prescribing functionality. Care coordinators, system navigators and discharge planners can easily find support services in the community and connect patients to them.</p></section>
<section class="content-section"><h2>Read our</h2><ul><li><a href="https://thlin.ca/Uploads/ContentDocuments/Responding_to_Section_3.3.2_of_the_Full_Application.pdf" target="_blank" rel="noopener">OHT application guidance document (PDF)</a></li><li><a href="https://thlin.ca/Uploads/ContentDocuments/DC_THL_White-Paper_2019-07-24.pdf" target="_blank" rel="noopener">Online Service Directories white paper (PDF)</a></li></ul></section>
HTML,
            'us' => <<<'HTML'
<section class="content-section"><h2>Our Story</h2><p>thehealthline.ca Information Network was founded in London (ON) in 2001 as a partnership of community, acute and public health care and launched our first online information resource the following year.</p><p>By 2009 we had not only expanded our footprint to eastern Ontario with a regional online information tool but also incorporated formally as a non-profit. In 2012 we were selected to provide the provincial online service directory, building on our work in southwestern and eastern Ontario.</p><p>Since then, we've continuously supported Ontario's online service directory, launched new products and services, built partnerships and continued to play an important role in Ontario's healthcare system. Through our platforms, we work with partners to improve information systems to better connect the people of Ontario to relevant health and community services in their area.</p><p><a class="btn btn-primary" href="/products/portfolio">Browse Our Portfolio</a></p></section>
HTML,
            'annual-reports' => <<<'HTML'
<section class="content-section"><h2>Annual Reports</h2><ul class="report-list"><li><a href="https://thlin.ca/Uploads/ContentDocuments/Annual-Report_2016-2017.pdf" target="_blank" rel="noopener">2016/2017 Annual Report (PDF)</a></li><li><a href="https://thlin.ca/Home/AnnualReport2018" target="_blank" rel="noopener">2017/2018 Annual Report</a></li><li><a href="https://thlin.ca/Home/AnnualReport2019" target="_blank" rel="noopener">2018/2019 Annual Report</a></li></ul></section>
HTML,
            'news' => <<<'HTML'
<p>Browse the latest news and updates from thehealthline.ca Information Network.</p>
HTML,
            'careers' => <<<'HTML'
<p>thehealthline.ca Information Network is a non-profit information company committed to making health and social service system navigation easier for everyone in Ontario. Located in London with workers connecting remotely throughout the province, we are a team-based, collaborative company.</p><p>For careers in the health care sector, visit Health Careers on <a href="https://www.southwesthealthline.ca" target="_blank" rel="noopener">southwesthealthline.ca</a>.</p>
HTML,
            'board' => <<<'HTML'
<p>Our Board of Directors provides governance and strategic direction for thehealthline.ca Information Network.</p>
HTML,
            'contact' => <<<'HTML'
<p>We work with partners to improve information systems and connect the people of Ontario to relevant health and community services. Let's talk about how we can collaborate to solve your clients' needs and your data management needs.</p>
HTML,
        ];
    }
}
